In [1]:
import torch

In [ ]:
#layer 1

In [5]:
in_channels = 3
out_channels = 10
kernel_size = (3,3)

In [154]:
#initiate weights 
torch.randn((out_channels,in_channels,*kernel_size))

NameError: name 'out_channels' is not defined

In [8]:
# layer2

In [9]:
in_channels = 10
out_channels = 10
kernel_size = (3,3)

#initialize weights
torch.randn((out_channels, in_channels, *kernel_size))

tensor([[[[ 9.7780e-01, -2.5650e+00,  4.5908e-01],
          [-6.5964e-01, -5.5390e-01, -2.3156e-01],
          [ 4.4518e-01, -8.4500e-01, -5.1839e-01]],

         [[-3.5526e-03,  1.5240e+00, -3.9857e-02],
          [-7.3219e-02, -1.2916e+00,  1.7444e-01],
          [ 7.9504e-02,  3.3009e-01, -2.5717e-02]],

         [[ 1.3604e+00, -1.9060e+00,  1.0994e+00],
          [-7.2749e-01, -2.0732e+00, -7.7894e-01],
          [-1.4691e+00,  1.6194e-01, -7.7943e-01]],

         [[-7.7918e-01,  1.1310e+00,  1.0559e+00],
          [ 3.0552e-01,  6.0789e-02, -6.7630e-01],
          [ 2.9063e-01, -1.1181e+00,  4.2425e-01]],

         [[-2.0772e+00, -5.5466e-01, -8.3448e-01],
          [-5.0678e-02,  9.0030e-01,  2.0078e-01],
          [-3.3117e-01, -1.2373e+00, -4.3185e-01]],

         [[-6.7557e-01, -6.3573e-01, -1.1711e+00],
          [ 1.2524e-02,  4.4757e-01,  1.8580e-01],
          [ 2.9108e-01, -1.2670e-01, -2.6969e-01]],

         [[ 1.6968e+00, -2.0797e+00,  2.1210e-01],
          [-6.6815e

In [1]:
import torch

In [25]:
class MaxPoolLayer:
    def __init__(self, size):
        self.last_input = None
        self.size = size

    def forward(self, x):
        self.last_input = x
        batch_size, channels, height, width = x.shape
        output_height = height // self.size
        output_width = width // self.size
        output = torch.zeros((batch_size, channels, output_height, output_width))
        print(output.shape)
        print(batch_size, channels)

        for i in range(output_height):
            for j in range(output_width):
                region = x[:, :, i * self.size:(i + 1) * self.size, j * self.size:(j + 1) * self.size].clone()
                print(region)
                print(region.view(batch_size, channels, -1))
                output[:, :, i, j] = torch.max(region.view(batch_size, channels, -1), dim=2)[0]

        return output

maxp = MaxPoolLayer(2)
maxp.forward(torch.randn(1,3,8,8))

torch.Size([1, 3, 4, 4])
1 3
tensor([[[[ 1.6427,  1.0322],
          [ 0.4579,  0.0647]],

         [[ 0.1017,  0.0574],
          [-1.0971, -0.0121]],

         [[ 0.5391, -0.7971],
          [-0.0425, -0.1239]]]])
tensor([[[ 1.6427,  1.0322,  0.4579,  0.0647],
         [ 0.1017,  0.0574, -1.0971, -0.0121],
         [ 0.5391, -0.7971, -0.0425, -0.1239]]])
tensor([[[[ 0.9477, -2.1046],
          [-0.8918,  1.1653]],

         [[ 0.3947,  0.0235],
          [-0.5901, -1.0602]],

         [[-0.5812,  2.2962],
          [ 0.4634,  0.1835]]]])
tensor([[[ 0.9477, -2.1046, -0.8918,  1.1653],
         [ 0.3947,  0.0235, -0.5901, -1.0602],
         [-0.5812,  2.2962,  0.4634,  0.1835]]])
tensor([[[[ 1.4651,  0.3512],
          [-0.8567,  0.9281]],

         [[-0.3210,  1.1427],
          [ 1.3828,  0.6929]],

         [[-1.3889,  1.3208],
          [ 0.9103,  2.2272]]]])
tensor([[[ 1.4651,  0.3512, -0.8567,  0.9281],
         [-0.3210,  1.1427,  1.3828,  0.6929],
         [-1.3889,  1.3208,  0

tensor([[[[ 1.6427,  1.1653,  1.4651,  2.1653],
          [ 1.3022,  0.9019, -0.5103,  1.2618],
          [ 1.8199,  2.3357,  0.9530,  2.7921],
          [ 1.7597,  1.2933,  1.6829,  1.5644]],

         [[ 0.1017,  0.3947,  1.3828,  1.7951],
          [ 1.8039,  1.7464,  1.8264,  1.4221],
          [ 0.9518,  0.1586, -0.1511,  1.1992],
          [ 0.9165,  1.0605,  1.1929,  0.8534]],

         [[ 0.5391,  2.2962,  2.2272,  1.7785],
          [ 1.5228,  1.7821,  1.2115, -0.2284],
          [ 0.9773,  0.0335,  0.8344,  1.5670],
          [ 1.2896,  0.4775,  0.3441,  0.8723]]]])

In [7]:
torch.randn(1,3,2,2),  torch.randn(1,3,2,2).view(1,3,-1) 

(tensor([[[[ 0.5773,  0.2666],
           [-0.7162, -2.4324]],
 
          [[ 1.1050, -0.5656],
           [-0.7531, -0.5193]],
 
          [[ 1.1093,  0.4929],
           [ 0.8521,  0.3785]]]]),
 tensor([[[ 1.6661, -0.1036, -1.9657, -0.7794],
          [ 0.5083, -0.5641, -0.9532,  2.4542],
          [ 1.8015,  1.1530,  0.6015, -1.0125]]]))

In [12]:
torch.max(torch.randn(1,3,2,2).view(1,3,-1) , dim = 1
         )

torch.return_types.max(
values=tensor([[0.7720, 0.4830, 1.1073, 1.2307]]),
indices=tensor([[0, 1, 1, 2]]))

In [3]:
out = torch.zeros(1,3,4,4)
out[:,:,1,1] = torch.max(torch.randn(1,3,2,2).view(1,3,-1) , dim = 2
         )[0]

In [4]:
out

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 1.4373, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.7581, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.8876, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]]])

In [6]:
(out>0).float()

tensor([[[[0., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [25]:
from typing import Tuple

class MaxPool2d:

    def __init__(self, 
                 kernel_size: int|Tuple,
                 stride: int|Tuple):
        self.kernel_size = (kernel_size 
                            if isinstance(kernel_size, tuple) and len(kernel_size) == 2 
                            else (kernel_size, kernel_size) 
                            if isinstance(kernel_size,int) else (2,2))
        self.stride = (stride 
                            if isinstance(stride, tuple) and len(stride) == 2 
                            else (stride, stride) 
                            if isinstance(stride,int) else (2,2))
        self.kh , self.kw = self.kernel_size
        self.sh, self.sw = self.stride

    def prepare_submatrix(self, X: torch.Tensor):
        B, C, ih, iw = X.shape
        oh = (ih - self.kh) // self.sh + 1
        ow = (iw - self.kw) // self.sw + 1
        subM = X.unfold(2, self.kh, self.sh).unfold(3,self.kw, self.sw)
        return subM

    def forward(self, X:torch.Tensor):
        subM = self.prepare_submatrix(X)
        return subM.max(dim = -1).values.max(dim = -1).values

    
    def add_padding(self,
                X: torch.Tensor,
                padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = X.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]
    
        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=X.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = X
        return padded_x

    def prepare_mask(self,
                     subm:torch.Tensor,
                     kh:int,
                     kw: int
                    ):
        B,C,oh,ow,kh,kw = subM.shape
        a = subm.view(-1, kh * kw)
        idx = torch.argmax(a ,dim=1)
        b = torch.zeros_like(a)
        b[torch.arange(b.shape[0]), idx] = 1
        mask = b.view(B,C, oh,ow, kh,kw)
        return mask

    def mask_dXp(self, mask: torch.Tensor,
                Xp: torch.Tensor,
                dz: torch.Tensor,
                kh: int,
                kw: int):
        dA = torch.einsum('i,ijk->ijk',
                         dz.view(-1),
                         mask.view(-1,kh,kw)).view(mask.shape)
        B,C,ih,iw = Xp.shape
        strides = (C * ih * iw, ih * iw, iw, 1)
        strides = tuple(i * Xp.element_size() for i in strides)
        dXp = torch.as_strided(dA, Xp.shape, strides)
        return dXp
        

    def maxpool_backprop(self,
                         dz:torch.Tensor,
                         X: torch.Tensor
                        ):
        Xp = self.add_padding(X, self.kernel_size[0])
        subM = self.prepare_submatrix(Xp)
        B,C,oh,ow,kh,kw = subM.shape
        B,C,ih,iw = Xp.shape

        mask = self.prepare_mask(subm, kh,kw)
        dXp = self.mask_dXp()
        
        
        

In [26]:
mxp = MaxPool2d(kernel_size=2,
               stride=2)

In [30]:
mxp1 = mxp.forward(x)

In [10]:
x = torch.randn(1,3,6,6)
x

tensor([[[[ 1.6551,  1.9962,  0.8629,  0.0646,  0.7071, -1.5948],
          [-1.5375,  1.0167, -0.1964, -0.7298, -0.9535, -1.1809],
          [-0.0379, -0.2264,  0.0209, -0.8308,  0.7298, -1.9761],
          [ 0.5598, -0.8292, -0.8335,  0.6953,  1.0632,  1.2825],
          [ 0.5851,  0.6493, -0.1973,  0.3548,  0.9868,  1.2589],
          [-1.9253, -0.4256, -1.4989, -0.9786,  0.1233,  0.9412]],

         [[-0.9156,  1.1602, -0.9697, -0.0564,  0.7820,  1.9830],
          [ 1.0401, -1.0526, -1.1813,  2.8026,  0.4501, -1.2441],
          [-2.3957, -1.2144,  0.9628, -1.1031, -0.7077,  0.7008],
          [ 3.0552,  2.4094,  1.0904, -0.3627,  0.1904, -0.3447],
          [ 0.2724, -1.4207,  0.1980,  0.9795,  0.7373, -0.1737],
          [-0.6485,  0.7355, -1.5282,  0.0914,  0.1053, -2.8584]],

         [[ 0.1064,  0.8753, -1.2745,  0.1193, -0.1274, -1.0164],
          [ 1.8251, -2.0244, -0.9216,  1.3951,  0.9372,  0.4867],
          [-0.2181,  0.0555, -0.7389,  1.7899, -0.0703,  0.5087],
      

In [21]:
x.unfold(2,2,2).unfold(3,2,2).max(dim = -1).values.max(dim = -1).values

tensor([[[[-0.4049,  0.4919,  1.0858],
          [ 0.9607,  1.5782,  1.3372],
          [ 1.1338,  1.3063,  1.8908]],

         [[ 1.5005,  0.7722,  0.6017],
          [ 0.9588,  1.6036,  1.1714],
          [ 1.2598,  1.0917,  1.8432]],

         [[ 0.4777,  0.6339,  1.2369],
          [ 0.9027,  0.0809,  1.9739],
          [ 1.0262,  1.7149,  1.7282]]]])

In [23]:
x.unfold(2,2,2).unfold(3,2,2).max(dim = -1).values.max(dim = -1).values.shape

torch.Size([1, 3, 3, 3])

ValueError: not enough values to unpack (expected 6, got 4)

In [17]:
x.unfold(2,2,2)

tensor([[[[[ 1.6551, -1.5375],
           [ 1.9962,  1.0167],
           [ 0.8629, -0.1964],
           [ 0.0646, -0.7298],
           [ 0.7071, -0.9535],
           [-1.5948, -1.1809]],

          [[-0.0379,  0.5598],
           [-0.2264, -0.8292],
           [ 0.0209, -0.8335],
           [-0.8308,  0.6953],
           [ 0.7298,  1.0632],
           [-1.9761,  1.2825]],

          [[ 0.5851, -1.9253],
           [ 0.6493, -0.4256],
           [-0.1973, -1.4989],
           [ 0.3548, -0.9786],
           [ 0.9868,  0.1233],
           [ 1.2589,  0.9412]]],


         [[[-0.9156,  1.0401],
           [ 1.1602, -1.0526],
           [-0.9697, -1.1813],
           [-0.0564,  2.8026],
           [ 0.7820,  0.4501],
           [ 1.9830, -1.2441]],

          [[-2.3957,  3.0552],
           [-1.2144,  2.4094],
           [ 0.9628,  1.0904],
           [-1.1031, -0.3627],
           [-0.7077,  0.1904],
           [ 0.7008, -0.3447]],

          [[ 0.2724, -0.6485],
           [-1.4207,  0.735

In [18]:
x.unfold(2,2,2).unfold(3,2,2)

tensor([[[[[[ 1.6551,  1.9962],
            [-1.5375,  1.0167]],

           [[ 0.8629,  0.0646],
            [-0.1964, -0.7298]],

           [[ 0.7071, -1.5948],
            [-0.9535, -1.1809]]],


          [[[-0.0379, -0.2264],
            [ 0.5598, -0.8292]],

           [[ 0.0209, -0.8308],
            [-0.8335,  0.6953]],

           [[ 0.7298, -1.9761],
            [ 1.0632,  1.2825]]],


          [[[ 0.5851,  0.6493],
            [-1.9253, -0.4256]],

           [[-0.1973,  0.3548],
            [-1.4989, -0.9786]],

           [[ 0.9868,  1.2589],
            [ 0.1233,  0.9412]]]],



         [[[[-0.9156,  1.1602],
            [ 1.0401, -1.0526]],

           [[-0.9697, -0.0564],
            [-1.1813,  2.8026]],

           [[ 0.7820,  1.9830],
            [ 0.4501, -1.2441]]],


          [[[-2.3957, -1.2144],
            [ 3.0552,  2.4094]],

           [[ 0.9628, -1.1031],
            [ 1.0904, -0.3627]],

           [[-0.7077,  0.7008],
            [ 0.1904, -0.3447]]],


In [29]:
mxp_ = x.unfold(2,2,2).unfold(3,2,2).max(dim = -1).values.max(dim = -1).values

In [41]:
print(torch.arange(0,10).unfold(0,2,2),'\n')
print(torch.arange(0,10).unfold(0,2,1))
print(torch.arange(0,10).unfold(0,2,3))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]) 

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7],
        [7, 8],
        [8, 9]])
tensor([[0, 1],
        [3, 4],
        [6, 7]])


In [34]:
(mxp1 == mxp_).all()

tensor(True)

In [54]:
import torch
import torch.nn.functional as F
from itertools import repeat


# Helper functions
def relu(x):
    return torch.clamp(x, min=0)


def relu_derivative(x):
    print(f"inside relu derivative  {x.shape}")
    return (x > 0).float()


def softmax(x):
    exps = torch.exp(x - torch.max(x, dim=1, keepdim=True)[0])
    return exps / torch.sum(exps, dim=1, keepdim=True)


def cross_entropy_loss(y_pred, y_true):
    n_samples = y_pred.shape[0]
    log_likelihood = -torch.log(y_pred[range(n_samples), y_true])
    return torch.sum(log_likelihood) / n_samples


def cross_entropy_loss_derivative(y_pred, y_true):
    n_samples = y_pred.shape[0]
    # grad = y_pred.clone()
    # grad[range(n_samples), y_true] -= 1
    # grad = grad / n_samples
    grad = F.softmax(y_pred, 1)
    grad[range(n_samples), y_true] -= 1
    grad = grad / n_samples
    return grad


# Custom Conv2d Layer
class Conv2d:
    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int,
                 stride: int = 1,
                 padding: int = 0,
                 dilation: int = 1,
                 groups: int = 1):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self._check_parameters()
        self._n_tuple()
        self.weights, self.bias = self.initialise_weights()

    def _n_tuple(self):
        self.kernel_size = (self.kernel_size, self.kernel_size)
        self.stride = (self.stride, self.stride)
        self.padding = (self.padding, self.padding)
        self.dilation = (self.dilation, self.dilation)

    def initialise_weights(self):
        return (torch.randn(self.out_channels, self.in_channels // self.groups, *self.kernel_size, requires_grad=True),
                torch.zeros(self.out_channels, requires_grad=True))

    def add_padding(self, x: torch.Tensor, padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = x.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=x.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = x
        return padded_x

    def _check_parameters(self):
        if self.groups <= 0:
            raise ValueError('groups must be a positive integer')
        if self.in_channels % self.groups != 0:
            raise ValueError('in_channels should be divisible by groups')
        if self.out_channels % self.groups != 0:
            raise ValueError('out_channels should be divisible by groups')

    def __call__(self, x: torch.Tensor):
        batch_size, in_channels, in_height, in_width = x.size()
        out_height = (in_height + 2 * self.padding[0] - self.dilation[0] * (self.kernel_size[0] - 1) - 1) // \
                     self.stride[0] + 1
        out_width = (in_width + 2 * self.padding[1] - self.dilation[1] * (self.kernel_size[1] - 1) - 1) // self.stride[
            1] + 1

        if self.padding[0] > 0 or self.padding[1] > 0:
            x = self.add_padding(x, self.padding[0])

        out = torch.zeros(batch_size, self.out_channels, out_height, out_width)

        for h in range(out_height):
            for w in range(out_width):
                h_start = h * self.stride[0]
                h_end = h_start + self.kernel_size[0]
                w_start = w * self.stride[1]
                w_end = w_start + self.kernel_size[1]
                receptive_field = x[:, :, h_start:h_end, w_start:w_end]

                out[:, :, h, w] = torch.sum(
                    receptive_field.unsqueeze(1) * self.weights.view(1, self.out_channels,
                                                                     self.in_channels // self.groups,
                                                                     *self.kernel_size),
                    dim=(2, 3, 4)
                ) + self.bias.view(1, self.out_channels)

        return out


# Max Pool Layer
from typing import Tuple

class MaxPool2d:

    def __init__(self, 
                 kernel_size: int|Tuple,
                 stride: int|Tuple):
        self.kernel_size = (kernel_size 
                            if isinstance(kernel_size, tuple) and len(kernel_size) == 2 
                            else (kernel_size, kernel_size) 
                            if isinstance(kernel_size,int) else (2,2))
        self.stride = (stride 
                            if isinstance(stride, tuple) and len(stride) == 2 
                            else (stride, stride) 
                            if isinstance(stride,int) else (2,2))
        self.kh , self.kw = self.kernel_size
        self.sh, self.sw = self.stride

    def prepare_submatrix(self, X: torch.Tensor):
        B, C, ih, iw = X.shape
        oh = (ih - self.kh) // self.sh + 1
        ow = (iw - self.kw) // self.sw + 1
        subM = X.unfold(2, self.kh, self.sh).unfold(3,self.kw, self.sw)
        return subM

    def forward(self, X:torch.Tensor):
        self.X = X
        subM = self.prepare_submatrix(X)
        return subM.max(dim = -1).values.max(dim = -1).values

    
    def add_padding(self,
                X: torch.Tensor,
                padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = X.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]
    
        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=X.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = X
        return padded_x

    def prepare_mask(self,
                     subM:torch.Tensor,
                     kh:int,
                     kw: int
                    ):
        B,C,oh,ow,kh,kw = subM.shape
        print(torch.reshape(subM,(-1, kh * kw)))
        # a = subM.view(-1, kh * kw)
        a = torch.reshape(subM,(-1, kh * kw))
        idx = torch.argmax(a ,dim=1)
        b = torch.zeros_like(a)
        b[torch.arange(b.shape[0]), idx] = 1
        mask = b.view(B,C, oh,ow, kh,kw)
        return mask

    def mask_dXp(self, mask: torch.Tensor,
                Xp: torch.Tensor,
                dz: torch.Tensor,
                kh: int,
                kw: int):
        dA = torch.einsum('i,ijk->ijk',
                         dz.view(-1),
                         mask.view(-1,kh,kw)).view(mask.shape)
        B,C,ih,iw = Xp.shape
        strides = (C * ih * iw, ih * iw, iw, 1)
        strides = tuple(i * Xp.element_size() for i in strides)
        dXp = torch.as_strided(dA, Xp.shape, strides)
        return dXp
        

    def maxpool_backprop(self,
                         dz:torch.Tensor,
                        ):
        X = self.X
        Xp = self.add_padding(X, self.kernel_size[0])
        subM = self.prepare_submatrix(Xp)
        B,C,oh,ow,kh,kw = subM.shape
        B,C,ih,iw = Xp.shape

        mask = self.prepare_mask(subM, kh,kw)
        dXp = self.mask_dXp(mask, Xp, dz, kh,kw)
        return dXp
        
                


# Fully Connected Layer
class FCLayer:
    def __init__(self, input_size, output_size):
        self.weights = torch.randn(input_size, output_size, requires_grad=True) / input_size
        self.biases = torch.zeros(output_size, requires_grad=True)

    def forward(self, x):
        self.last_input_shape = x.shape
        self.last_input = x.view(x.shape[0], -1)
        # return torch.matmul(self.last_input, self.weights) + self.biases
        return (self.last_input @ self.weights) + self.biases
    def backward(self, d_L_d_out, lr):
        # d_L_d_weights = torch.matmul(self.last_input.t(), d_L_d_out)
        print(f"shape of self.last_ip {self.last_input.shape} , shape of self.d_L_d_out {d_L_d_out.shape}"
              f"shape of self.weights {self.weights.shape}")
        d_L_d_weights = self.last_input.T @ d_L_d_out
        print(f"shape of d_L_d_weights {d_L_d_weights.shape}")
        d_L_d_biases = torch.sum(d_L_d_out, dim=0)

        d_L_d_input = d_L_d_out @ self.weights.T
        self.weights = self.weights - lr * d_L_d_weights
        self.biases = self.biases - lr * d_L_d_biases

        return d_L_d_input


# Model
class CNN:
    def __init__(self):
        self.conv = Conv2d(3, 8, 3)
        self.pool = MaxPool2d(2,2)
        self.fc = FCLayer(8 * 15 * 15, 128)
        self.output = FCLayer(128, 3)

    def forward(self, x):
        x = self.conv(x)
        print(f"shape after convolution {x.shape} ")
        x = relu(x)
        print(f"shape after relu {x.shape} ")
        x = self.pool.forward(x)
        print(f"shape after max pool {x.shape} ")
        x = self.fc.forward(x)
        print(f"shape after fc layer {x.shape} ")
        x = relu(x)
        print(f"shape after relu 2 {x.shape} ")
        x = self.output.forward(x)
        print(f"shape after FCL output {x.shape} ")
        return softmax(x)

    def train(self, x_train, y_train, lr=0.001):
        out = self.forward(x_train)
        loss = cross_entropy_loss(out, y_train)
        print(f'Loss: {loss.item()}')

        grad = cross_entropy_loss_derivative(out, y_train)
        # print(grad.shape)
        grad = self.output.backward(grad, lr)
        # print(grad.shape)
        grad = relu_derivative(self.fc.backward(grad, lr))
        print(grad.shape)
        grad = self.pool.maxpool_backprop(grad)
        grad = relu_derivative(self.conv.backward(grad, lr))

        return loss


# Create random x_train and y_train
torch.manual_seed(42)
x_train = torch.randn(10, 3, 32, 32)  # 10 samples, 3 channels, 32x32 images
y_train = torch.randint(0, 3, (10,))  # 10 samples, 3 classes

# Example usage
cnn = CNN()
for epoch in range(10):  # Reduced epochs for example purposes
    loss = cnn.train(x_train, y_train)
    break


shape after convolution torch.Size([10, 8, 30, 30]) 
shape after relu torch.Size([10, 8, 30, 30]) 
shape after max pool torch.Size([10, 8, 15, 15]) 
shape after fc layer torch.Size([10, 128]) 
shape after relu 2 torch.Size([10, 128]) 
shape after FCL output torch.Size([10, 3]) 
Loss: 1.094382643699646
shape of self.last_ip torch.Size([10, 128]) , shape of self.d_L_d_out torch.Size([10, 3])shape of self.weights torch.Size([128, 3])
shape of d_L_d_weights torch.Size([128, 3])
shape of self.last_ip torch.Size([10, 1800]) , shape of self.d_L_d_out torch.Size([10, 128])shape of self.weights torch.Size([1800, 128])
shape of d_L_d_weights torch.Size([1800, 128])
inside relu derivative  torch.Size([10, 1800])
torch.Size([10, 1800])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], grad_fn=<UnsafeViewBackward0>)


RuntimeError: einsum(): subscript i has size 23120 for operand 1 which does not broadcast with previously seen size 18000

In [45]:
a =torch.randn(10, 8, 17, 17, 2, 2)
b = a.view(-1, 4)

In [55]:
import torch
import torch.nn.functional as F
from itertools import repeat


# Helper functions
def relu(x):
    return torch.clamp(x, min=0)


def relu_derivative(x):
    return (x > 0).float()


def softmax(x):
    exps = torch.exp(x - torch.max(x, dim=1, keepdim=True)[0])
    return exps / torch.sum(exps, dim=1, keepdim=True)


def cross_entropy_loss(y_pred, y_true):
    n_samples = y_pred.shape[0]
    log_likelihood = -torch.log(y_pred[range(n_samples), y_true])
    return torch.sum(log_likelihood) / n_samples


def cross_entropy_loss_derivative(y_pred, y_true):
    n_samples = y_pred.shape[0]
    grad = F.softmax(y_pred, 1)
    grad[range(n_samples), y_true] -= 1
    grad = grad / n_samples
    return grad


# Custom Conv2d Layer
class Conv2d:
    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int,
                 stride: int = 1,
                 padding: int = 0,
                 dilation: int = 1,
                 groups: int = 1):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self._check_parameters()
        self._n_tuple()
        self.weights, self.bias = self.initialise_weights()

    def _n_tuple(self):
        self.kernel_size = (self.kernel_size, self.kernel_size)
        self.stride = (self.stride, self.stride)
        self.padding = (self.padding, self.padding)
        self.dilation = (self.dilation, self.dilation)

    def initialise_weights(self):
        return (torch.randn(self.out_channels, self.in_channels // self.groups, *self.kernel_size, requires_grad=True),
                torch.zeros(self.out_channels, requires_grad=True))

    def add_padding(self, x: torch.Tensor, padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = x.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=x.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = x
        return padded_x

    def _check_parameters(self):
        if self.groups <= 0:
            raise ValueError('groups must be a positive integer')
        if self.in_channels % self.groups != 0:
            raise ValueError('in_channels should be divisible by groups')
        if self.out_channels % self.groups != 0:
            raise ValueError('out_channels should be divisible by groups')

    def __call__(self, x: torch.Tensor):
        batch_size, in_channels, in_height, in_width = x.size()
        out_height = (in_height + 2 * self.padding[0] - self.dilation[0] * (self.kernel_size[0] - 1) - 1) // \
                     self.stride[0] + 1
        out_width = (in_width + 2 * self.padding[1] - self.dilation[1] * (self.kernel_size[1] - 1) - 1) // self.stride[
            1] + 1

        if self.padding[0] > 0 or self.padding[1] > 0:
            x = self.add_padding(x, self.padding[0])

        out = torch.zeros(batch_size, self.out_channels, out_height, out_width)

        for h in range(out_height):
            for w in range(out_width):
                h_start = h * self.stride[0]
                h_end = h_start + self.kernel_size[0]
                w_start = w * self.stride[1]
                w_end = w_start + self.kernel_size[1]
                receptive_field = x[:, :, h_start:h_end, w_start:w_end]

                out[:, :, h, w] = torch.sum(
                    receptive_field.unsqueeze(1) * self.weights.view(1, self.out_channels,
                                                                     self.in_channels // self.groups,
                                                                     *self.kernel_size),
                    dim=(2, 3, 4)
                ) + self.bias.view(1, self.out_channels)

        return out


# Max Pool Layer
from typing import Tuple

class MaxPool2d:
    def __init__(self, 
                 kernel_size: int|Tuple,
                 stride: int|Tuple):
        self.kernel_size = (kernel_size 
                            if isinstance(kernel_size, tuple) and len(kernel_size) == 2 
                            else (kernel_size, kernel_size) 
                            if isinstance(kernel_size,int) else (2,2))
        self.stride = (stride 
                            if isinstance(stride, tuple) and len(stride) == 2 
                            else (stride, stride) 
                            if isinstance(stride,int) else (2,2))
        self.kh , self.kw = self.kernel_size
        self.sh, self.sw = self.stride

    def prepare_submatrix(self, X: torch.Tensor):
        B, C, ih, iw = X.shape
        oh = (ih - self.kh) // self.sh + 1
        ow = (iw - self.kw) // self.sw + 1
        subM = X.unfold(2, self.kh, self.sh).unfold(3, self.kw, self.sw)
        return subM

    def forward(self, X: torch.Tensor):
        self.X = X
        subM = self.prepare_submatrix(X)
        return subM.max(dim=-1).values.max(dim=-1).values

    def add_padding(self, X: torch.Tensor, padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = X.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=X.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = X
        return padded_x

    def prepare_mask(self, subM: torch.Tensor, kh: int, kw: int):
        B, C, oh, ow, kh, kw = subM.shape
        a = torch.reshape(subM, (-1, kh * kw))
        idx = torch.argmax(a, dim=1)
        b = torch.zeros_like(a)
        b[torch.arange(b.shape[0]), idx] = 1
        mask = b.view(B, C, oh, ow, kh, kw)
        return mask

    def mask_dXp(self, mask: torch.Tensor, Xp: torch.Tensor, dz: torch.Tensor, kh: int, kw: int):
        dA = torch.einsum('i,ijk->ijk', dz.view(-1), mask.view(-1, kh, kw)).view(mask.shape)
        B, C, ih, iw = Xp.shape
        strides = (C * ih * iw, ih * iw, iw, 1)
        strides = tuple(i * Xp.element_size() for i in strides)
        dXp = torch.as_strided(dA, Xp.shape, strides)
        return dXp

    def maxpool_backprop(self, dz: torch.Tensor):
        X = self.X
        Xp = self.add_padding(X, self.kernel_size[0])
        subM = self.prepare_submatrix(Xp)
        B, C, oh, ow, kh, kw = subM.shape
        B, C, ih, iw = Xp.shape

        mask = self.prepare_mask(subM, kh, kw)
        dXp = self.mask_dXp(mask, Xp, dz, kh, kw)
        return dXp


# Fully Connected Layer
class FCLayer:
    def __init__(self, input_size, output_size):
        self.weights = torch.randn(input_size, output_size, requires_grad=True) / input_size
        self.biases = torch.zeros(output_size, requires_grad=True)

    def forward(self, x):
        self.last_input_shape = x.shape
        self.last_input = x.view(x.shape[0], -1)
        return (self.last_input @ self.weights) + self.biases

    def backward(self, d_L_d_out, lr):
        d_L_d_weights = self.last_input.T @ d_L_d_out
        d_L_d_biases = d_L_d_out.sum(axis=0)
        d_L_d_input = d_L_d_out @ self.weights.T
        self.weights.grad = d_L_d_weights
        self.biases.grad = d_L_d_biases
        self.weights = self.weights - lr * d_L_d_weights
        self.biases = self.biases - lr * d_L_d_biases
        return d_L_d_input.view(self.last_input_shape)


# Model definition
class SimpleCNN:
    def __init__(self):
        self.conv1 = Conv2d(1, 8, kernel_size=3, stride=1, padding=1)
        self.pool1 = MaxPool2d(kernel_size=2, stride=2)
        self.fc1 = FCLayer(14 * 14 * 8, 128)
        self.fc2 = FCLayer(128, 10)

    def forward(self, x):
        x = relu(self.conv1(x))
        x = self.pool1.forward(x)
        x = relu(self.fc1.forward(x))
        x = self.fc2.forward(x)
        return x

    def backward(self, dL_dy, lr):
        dL_dy = self.fc2.backward(dL_dy, lr)
        dL_dy = self.fc1.backward(dL_dy, lr)
        dL_dy = self.pool1.maxpool_backprop(dL_dy)
        dL_dy = dL_dy * relu_derivative(self.conv1.forward(self.pool1.X))
        self.conv1.weights.grad = torch.einsum('ijkl,ijmn->jklm', dL_dy, self.pool1.X)
        self.conv1.bias.grad = dL_dy.sum(dim=(0, 2, 3))
        self.conv1.weights -= lr * self.conv1.weights.grad
        self.conv1.bias -= lr * self.conv1.bias.grad


# Training loop (example)
def train(model, criterion, optimizer, train_loader, num_epochs=5):
    for epoch in range(num_epochs):
        for i, (images, labels) in enumerate(train_loader):
            # Forward pass
            outputs = model.forward(images)
            loss = criterion(outputs, labels)

            # Backward pass and optimization
            dL_dy = cross_entropy_loss_derivative(outputs, labels)
            model.backward(dL_dy, lr=0.001)

            if (i + 1) % 100 == 0:
                print(f'Epoch [{epoch + 1}/{num_epochs}], Step [{i + 1}/{len(train_loader)}], Loss: {loss.item():.4f}')

torch.manual_seed(42)
x_train = torch.randn(10, 3, 32, 32)  # 10 samples, 3 channels, 32x32 images
y_train = torch.randint(0, 3, (10,))  # 10 samples, 3 classes

# Example usage
cnn = CNN()
for epoch in range(10):  # Reduced epochs for example purposes
    loss = cnn.train(x_train, y_train)
    break


In [56]:
import torch
from torch.utils.data import DataLoader, TensorDataset

# Create synthetic dataset
def create_synthetic_data(num_samples=1000):
    # Generate random images of size 28x28 with 1 channel (grayscale)
    images = torch.randn(num_samples, 1, 28, 28)
    # Generate random labels (10 classes)
    labels = torch.randint(0, 10, (num_samples,))
    return images, labels

# Create DataLoader
def get_dataloader(batch_size=32, num_samples=1000):
    images, labels = create_synthetic_data(num_samples)
    dataset = TensorDataset(images, labels)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    return dataloader

# Instantiate the model
model = SimpleCNN()

# Define the criterion
criterion = cross_entropy_loss

# Get the DataLoader
train_loader = get_dataloader()

# Training loop
train(model, criterion, None, train_loader, num_epochs=5)


RuntimeError: einsum(): subscript i has size 65536 for operand 1 which does not broadcast with previously seen size 50176

In [57]:
import torch
import torch.nn.functional as F
from itertools import repeat
from typing import Tuple


# Helper functions
def relu(x):
    return torch.clamp(x, min=0)


def relu_derivative(x):
    return (x > 0).float()


def softmax(x):
    exps = torch.exp(x - torch.max(x, dim=1, keepdim=True)[0])
    return exps / torch.sum(exps, dim=1, keepdim=True)


def cross_entropy_loss(y_pred, y_true):
    n_samples = y_pred.shape[0]
    log_likelihood = -torch.log(y_pred[range(n_samples), y_true])
    return torch.sum(log_likelihood) / n_samples


def cross_entropy_loss_derivative(y_pred, y_true):
    n_samples = y_pred.shape[0]
    grad = F.softmax(y_pred, dim=1)
    grad[range(n_samples), y_true] -= 1
    grad = grad / n_samples
    return grad


# Custom Conv2d Layer
class Conv2d:
    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int,
                 stride: int = 1,
                 padding: int = 0,
                 dilation: int = 1,
                 groups: int = 1):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self._check_parameters()
        self._n_tuple()
        self.weights, self.bias = self.initialise_weights()

    def _n_tuple(self):
        self.kernel_size = (self.kernel_size, self.kernel_size)
        self.stride = (self.stride, self.stride)
        self.padding = (self.padding, self.padding)
        self.dilation = (self.dilation, self.dilation)

    def initialise_weights(self):
        return (torch.randn(self.out_channels, self.in_channels // self.groups, *self.kernel_size, requires_grad=True),
                torch.zeros(self.out_channels, requires_grad=True))

    def add_padding(self, x: torch.Tensor, padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = x.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=x.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = x
        return padded_x

    def _check_parameters(self):
        if self.groups <= 0:
            raise ValueError('groups must be a positive integer')
        if self.in_channels % self.groups != 0:
            raise ValueError('in_channels should be divisible by groups')
        if self.out_channels % self.groups != 0:
            raise ValueError('out_channels should be divisible by groups')

    def forward(self, x: torch.Tensor):
        batch_size, in_channels, in_height, in_width = x.size()
        out_height = (in_height + 2 * self.padding[0] - self.dilation[0] * (self.kernel_size[0] - 1) - 1) // \
                     self.stride[0] + 1
        out_width = (in_width + 2 * self.padding[1] - self.dilation[1] * (self.kernel_size[1] - 1) - 1) // self.stride[
            1] + 1

        if self.padding[0] > 0 or self.padding[1] > 0:
            x = self.add_padding(x, self.padding[0])

        out = torch.zeros(batch_size, self.out_channels, out_height, out_width)

        for h in range(out_height):
            for w in range(out_width):
                h_start = h * self.stride[0]
                h_end = h_start + self.kernel_size[0]
                w_start = w * self.stride[1]
                w_end = w_start + self.kernel_size[1]
                receptive_field = x[:, :, h_start:h_end, w_start:w_end]

                out[:, :, h, w] = torch.sum(
                    receptive_field.unsqueeze(1) * self.weights.view(1, self.out_channels,
                                                                     self.in_channels // self.groups,
                                                                     *self.kernel_size),
                    dim=(2, 3, 4)
                ) + self.bias.view(1, self.out_channels)

        self.last_input = x
        return out


# Max Pool Layer
class MaxPool2d:
    def __init__(self, 
                 kernel_size: int | Tuple[int, int],
                 stride: int | Tuple[int, int]):
        self.kernel_size = (kernel_size 
                            if isinstance(kernel_size, tuple) and len(kernel_size) == 2 
                            else (kernel_size, kernel_size) 
                            if isinstance(kernel_size, int) else (2, 2))
        self.stride = (stride 
                       if isinstance(stride, tuple) and len(stride) == 2 
                       else (stride, stride) 
                       if isinstance(stride, int) else (2, 2))
        self.kh, self.kw = self.kernel_size
        self.sh, self.sw = self.stride

    def prepare_submatrix(self, X: torch.Tensor):
        B, C, ih, iw = X.shape
        oh = (ih - self.kh) // self.sh + 1
        ow = (iw - self.kw) // self.sw + 1
        subM = X.unfold(2, self.kh, self.sh).unfold(3, self.kw, self.sw)
        return subM

    def forward(self, X: torch.Tensor):
        self.X = X
        subM = self.prepare_submatrix(X)
        return subM.max(dim=-1).values.max(dim=-1).values

    def add_padding(self,
                    X: torch.Tensor,
                    padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = X.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=X.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = X
        return padded_x

    def prepare_mask(self,
                     subM: torch.Tensor,
                     kh: int,
                     kw: int):
        B, C, oh, ow, kh, kw = subM.shape
        a = torch.reshape(subM, (-1, kh * kw))
        idx = torch.argmax(a, dim=1)
        b = torch.zeros_like(a)
        b[torch.arange(b.shape[0]), idx] = 1
        mask = b.view(B, C, oh, ow, kh, kw)
        return mask

    def mask_dXp(self, mask: torch.Tensor,
                 Xp: torch.Tensor,
                 dz: torch.Tensor,
                 kh: int,
                 kw: int):
        dA = torch.einsum('i,ijk->ijk',
                          dz.view(-1),
                          mask.view(-1, kh, kw)).view(mask.shape)
        B, C, ih, iw = Xp.shape
        strides = (C * ih * iw, ih * iw, iw, 1)
        strides = tuple(i * Xp.element_size() for i in strides)
        dXp = torch.as_strided(dA, Xp.shape, strides)
        return dXp

    def maxpool_backprop(self,
                         dz: torch.Tensor):
        X = self.X
        Xp = self.add_padding(X, self.kernel_size[0])
        subM = self.prepare_submatrix(Xp)
        B, C, oh, ow, kh, kw = subM.shape
        B, C, ih, iw = Xp.shape

        mask = self.prepare_mask(subM, kh, kw)
        dXp = self.mask_dXp(mask, Xp, dz, kh, kw)
        return dXp


# Fully Connected Layer
class FCLayer:
    def __init__(self, input_size, output_size):
        self.weights = torch.randn(input_size, output_size, requires_grad=True) / input_size
        self.biases = torch.zeros(output_size, requires_grad=True)

    def forward(self, x):
        self.last_input_shape = x.shape
        self.last_input = x.view(x.shape[0], -1)
        return (self.last_input @ self.weights) + self.biases

    def backward(self, d_L_d_out, lr):
        d_L_d_weights = self.last_input.T @ d_L_d_out
        d_L_d_biases = torch.sum(d_L_d_out, dim=0)

        d_L_d_input = d_L_d_out @ self.weights.T
        d_L_d_input = d_L_d_input.view(self.last_input_shape)

        self.weights = self.weights - lr * d_L_d_weights
        self.biases = self.biases - lr * d_L_d_biases

        return d_L_d_input


# Model
class SimpleCNN:
    def __init__(self):
        self.conv1 = Conv2d(1, 8, 3)
        self.pool = MaxPool2d(2, 2)
        self.conv2 = Conv2d(8, 16, 3)
        self.fc1 = FCLayer(16 * 5 * 5, 120)
        self.fc2 = FCLayer(120, 84)
        self.fc3 = FCLayer(84, 10)

    def forward(self, x):
        x = relu(self.conv1.forward(x))
        x = self.pool.forward(x)
        x = relu(self.conv2.forward(x))
        x = self.pool.forward(x)
        x = relu(self.fc1.forward(x))
        x = relu(self.fc2.forward(x))
        x = self.fc3.forward(x)
        return x


# Training function
def train(model, criterion, optimizer, dataloader, num_epochs=5):
    for epoch in range(num_epochs):
        for i, (inputs, labels) in enumerate(dataloader):
            outputs = model.forward(inputs)
            loss = criterion(outputs, labels)
            print(f"Epoch {epoch + 1}/{num_epochs}, Batch {i + 1}/{len(dataloader)}, Loss: {loss.item()}")

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()


# Optimizer placeholder
class Optimizer:
    def __init__(self, params, lr):
        self.params = params
        self.lr = lr

    def zero_grad(self):
        for param in self.params:
            if param.grad is not None:
                param.grad.detach_()
                param.grad.zero_()

    def step(self):
        for param in self.params:
            if param.grad is not None:
                param.data -= self.lr * param.grad


# Instantiate the model and optimizer
model = SimpleCNN()
params = [model.conv1.weights, model.conv1.bias,
          model.conv2.weights, model.conv2.bias,
          model.fc1.weights, model.fc1.biases,
          model.fc2.weights, model.fc2.biases,
          model.fc3.weights, model.fc3.biases]
optimizer = Optimizer(params, lr=0.001)

# Create synthetic dataset
def create_synthetic_data(num_samples=1000):
    # Generate random images of size 28x28 with 1 channel (grayscale)
    images = torch.randn(num_samples, 1, 28, 28)
    # Generate random labels (10 classes)
    labels = torch.randint(0, 10, (num_samples,))
    return images, labels

# Create DataLoader
def get_dataloader(batch_size=32, num_samples=1000):
    images, labels = create_synthetic_data(num_samples)
    dataset = TensorDataset(images, labels)
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    return dataloader

# Define the criterion
criterion = cross_entropy_loss

# Get the DataLoader
train_loader = get_dataloader()

# Training loop
train(model, criterion, optimizer, train_loader, num_epochs=5)


Epoch 1/5, Batch 1/32, Loss: nan


C:\Users\CD138JR\AppData\Local\Temp\ipykernel_39268\3658936679.py:260: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  if param.grad is not None:
C:\Users\CD138JR\AppData\Local\Temp\ipykernel_39268\3658936679.py:266: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you a

Epoch 1/5, Batch 2/32, Loss: nan


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

## New Version

### Maxpool2D

In [58]:
class MaxPool2d:

    def __init__(self, 
                 kernel_size: int|Tuple,
                 stride: int|Tuple):
        self.kernel_size = (kernel_size 
                            if isinstance(kernel_size, tuple) and len(kernel_size) == 2 
                            else (kernel_size, kernel_size) 
                            if isinstance(kernel_size,int) else (2,2))
        self.stride = (stride 
                            if isinstance(stride, tuple) and len(stride) == 2 
                            else (stride, stride) 
                            if isinstance(stride,int) else (2,2))
        self.kh , self.kw = self.kernel_size
        self.sh, self.sw = self.stride

    def prepare_submatrix(self, X: torch.Tensor):
        B, C, ih, iw = X.shape
        oh = (ih - self.kh) // self.sh + 1
        ow = (iw - self.kw) // self.sw + 1
        subM = X.unfold(2, self.kh, self.sh).unfold(3,self.kw, self.sw)
        return subM

    def forward(self, X:torch.Tensor):
        self.X = X
        subM = self.prepare_submatrix(X)
        return subM.max(dim = -1).values.max(dim = -1).values

    
    def add_padding(self,
                X: torch.Tensor,
                padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = X.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]
    
        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=X.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = X
        return padded_x

    def prepare_mask(self,
                     subM:torch.Tensor,
                     kh:int,
                     kw: int
                    ):
        B,C,oh,ow,kh,kw = subM.shape
        print(torch.reshape(subM,(-1, kh * kw)))
        # a = subM.view(-1, kh * kw)
        a = torch.reshape(subM,(-1, kh * kw))
        idx = torch.argmax(a ,dim=1)
        b = torch.zeros_like(a)
        b[torch.arange(b.shape[0]), idx] = 1
        mask = b.view(B,C, oh,ow, kh,kw)
        return mask

    def mask_dXp(self, mask: torch.Tensor,
                Xp: torch.Tensor,
                dz: torch.Tensor,
                kh: int,
                kw: int):
        dA = torch.einsum('i,ijk->ijk',
                         dz.view(-1),
                         mask.view(-1,kh,kw)).view(mask.shape)
        B,C,ih,iw = Xp.shape
        strides = (C * ih * iw, ih * iw, iw, 1)
        strides = tuple(i * Xp.element_size() for i in strides)
        dXp = torch.as_strided(dA, Xp.shape, strides)
        return dXp

    def parameters(Self):
        return []

## Activations 

In [156]:
class Relu:

    def __call__(self, 
                 X: torch.Tensor):
        return torch.clamp(X, min=0)

    def backward(self, 
                 dZ:torch.Tensor):
        return (dZ > 0).float

    def parameters(self):
        return []
        

In [65]:
rel = torch.randn(4,4)
rel

tensor([[-1.2437, -1.3459,  0.0191, -0.3140],
        [-0.8502, -1.6319,  1.1911, -2.5889],
        [-0.3407, -0.5172, -1.7387, -0.4112],
        [ 0.2187,  0.5901, -0.6600, -0.4221]])

In [70]:
rel * (rel > 0)

tensor([[-0.0000, -0.0000, 0.0191, -0.0000],
        [-0.0000, -0.0000, 1.1911, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000],
        [0.2187, 0.5901, -0.0000, -0.0000]])

In [73]:
torch.clamp(rel, min=0)

tensor([[0.0000, 0.0000, 0.0191, 0.0000],
        [0.0000, 0.0000, 1.1911, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.2187, 0.5901, 0.0000, 0.0000]])

In [74]:
(rel > 0).float()

tensor([[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [1., 1., 0., 0.]])

### Softmax

In [158]:
class Softmax:

    def __call__(self, 
                X: torch.Tensor, 
                dim: int):
        X = X - torch.max(X, dim = 1, keepdims = True).values
        sof = torch.exp(X)/torch.sum(torch.exp(X), dim = dim , keepdims = True)

    def parameters(self):
        return []
        

In [107]:
# Its not needeed  to calculate tghe gradients for the softmax since the softymax is being used in calculating the Cross Entropy Loss
#the gradients from the CE loss is suffiecient

In [75]:
torch.randn(2,3)

tensor([[-1.5686, -1.1641,  1.7440],
        [-0.7862, -1.7022,  0.4724]])

In [92]:
x = torch.randn(2,3)
print(x)
x = x - torch.max(x, dim = 1, keepdims = True).values

tensor([[-0.9029,  2.1909, -0.7375],
        [ 1.5797,  1.1408,  0.9713]])


In [90]:
torch.max(x, dim =1 , keepdim = True)

torch.return_types.max(
values=tensor([[0.],
        [0.]]),
indices=tensor([[0],
        [0]]))

In [94]:
x

tensor([[-3.0938,  0.0000, -2.9284],
        [ 0.0000, -0.4390, -0.6085]])

In [103]:
torch.exp(x)/torch.sum(torch.exp(x), dim = 1 , keepdims = True)

tensor([[0.0413, 0.9101, 0.0487],
        [0.4569, 0.2945, 0.2486]])

In [104]:
import torch

class Softmax:
    def __call__(self, x: torch.Tensor):
        x = x - x.max(dim=1, keepdim=True).values
        exp_x = torch.exp(x)
        self.softmax_output = exp_x / exp_x.sum(dim=1, keepdim=True)
        return self.softmax_output

    def backward(self, dZ: torch.Tensor):
        if len(dZ.shape) == 1:
            dZ.unsqueeze_(dim=0)
            
        batch_size, num_classes = dZ.shape
        dX = torch.empty_like(dZ)
        
        for i in range(batch_size):
            s = self.softmax_output[i].unsqueeze(1)
            jacobian_matrix = torch.diagflat(s) - s @ s.T
            dX[i] = dZ[i] @ jacobian_matrix

        return dX

# Example usage
softmax = Softmax()

# Forward pass
x = torch.tensor([[1.0, 2.0, 3.0], [1.0, 2.0, -1.0]])
output = softmax(x)
print("Softmax Output:")
print(output)

# Backward pass (assuming some gradient from the next layer)
dZ = torch.tensor([[0.1, 0.2, -0.3], [0.4, -0.5, 0.1]])
dX = softmax.backward(dZ)
print("Gradient wrt Input:")
print(dX)


Softmax Output:
tensor([[0.0900, 0.2447, 0.6652],
        [0.2595, 0.7054, 0.0351]])
Gradient wrt Input:
tensor([[ 0.0218,  0.0836, -0.1054],
        [ 0.1675, -0.1796,  0.0121]])


 ### Loss - Cross Entropy

In [110]:
class CrossEntropyLoss:

    def __call__(self,
                 y_pred: torch.Tensor,
                 y_true: torch.Tensor
                ):
        n_samples = y_pred.shape[0]
        log_likelihood = -torch.log(y_pred[range(n_samples), y_true])
        return torch.sum(log_likelihood) / n_samples

    def backward(self,
                y_pred: torch.Tensor,
                y_true: torch.Tensor
                ):
        n_samples = y_pred.shape[0]
        softmax = Softmax()
        grad = softmax(y_pred, dim=1)
        grad[range(n_samples), y_true] -= 1
        grad = grad / n_samples
        return grad

    def paramerters(self):
        return []

    
    

In [138]:
x = torch.rand(10,4)
x

tensor([[0.9969, 0.2697, 0.7932, 0.6488],
        [0.0515, 0.4998, 0.1391, 0.5888],
        [0.1619, 0.6078, 0.9070, 0.1058],
        [0.3053, 0.7272, 0.0810, 0.2980],
        [0.7713, 0.9617, 0.2650, 0.0125],
        [0.3623, 0.2542, 0.2724, 0.4133],
        [0.0827, 0.4158, 0.6465, 0.4369],
        [0.0306, 0.0630, 0.8786, 0.2498],
        [0.7035, 0.7723, 0.3581, 0.4975],
        [0.8384, 0.5916, 0.9916, 0.5968]])

In [143]:
y = torch.randint(0,4, (10,))
y

tensor([3, 0, 0, 0, 0, 3, 2, 1, 0, 0])

In [144]:
loss = CrossEntropyLoss()
loss(x,y)

tensor(1.1278)

In [151]:
x[range(10), y]

tensor([0.6488, 0.0515, 0.1619, 0.3053, 0.7713, 0.4133, 0.6465, 0.0630, 0.7035,
        0.8384])

## Optimizer -SGD

In [152]:
from typing import Optional , List
class OptimizerSG:

    def __init__(self,
                params: Optional[List],
                lr : float = 0.1):
        self.params = params
        self.lr = lr

    def step(self):
        for param in self.params:
            if param.grad is not None:
                param.data -= self.lr * param.grad


## Flatten Layer


In [155]:
class Flatten:

    def __call__(self,
                X: torch.Tensor):
        self.X = X
        self.out = X.view(X.shape[0], -1)
        return self.out

    def backward(self,
                 dZ: torch.Tensor):
        dX = dZ.view(self.X.size)
        return dX 
    
    def parameters(self):
        return []

        

In [160]:
x.size()

torch.Size([10, 4])

## Sequential

In [162]:
class Sequential:
    def __init__(self, 
                layers: List):
        self.layers = layers

    def __call__(self,
                X: torch.Tensor):
        for layer in self.layers:
            X = layer(X)
        self.out = X
        return self.out

    def parameters(self):
        return [p for layer in self.parameters for p in layer.parameters()]


## Convultion2D

In [163]:
# Custom Conv2d Layer
class Conv2d:
    def __init__(self,
                 in_channels: int,
                 out_channels: int,
                 kernel_size: int,
                 stride: int = 1,
                 padding: int = 0,
                 dilation: int = 1,
                 groups: int = 1):
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self._check_parameters()
        self._n_tuple()
        self.weights, self.bias = self.initialise_weights()

    def _n_tuple(self):
        self.kernel_size = (self.kernel_size, self.kernel_size)
        self.stride = (self.stride, self.stride)
        self.padding = (self.padding, self.padding)
        self.dilation = (self.dilation, self.dilation)

    def initialise_weights(self):
        return (torch.randn(self.out_channels, self.in_channels // self.groups, *self.kernel_size, requires_grad=True),
                torch.zeros(self.out_channels, requires_grad=True))

    def add_padding(self, x: torch.Tensor, padding: int):
        padding = tuple(repeat(padding, 4))
        batch_size, in_channels, original_height, original_width = x.size()
        padded_height = original_height + padding[0] + padding[1]
        padded_width = original_width + padding[2] + padding[3]

        if (self.padded_height and self.padded_width) is None:
            self.padded_height, self.padded_width = padded_height, padded_width

        padded_x = torch.zeros((batch_size, in_channels, padded_height, padded_width), dtype=x.dtype)
        padded_x[:, :, padding[0]:padding[0] + original_height, padding[2]:padding[2] + original_width] = x
        return padded_x

    def _check_parameters(self):
        if self.groups <= 0:
            raise ValueError('groups must be a positive integer')
        if self.in_channels % self.groups != 0:
            raise ValueError('in_channels should be divisible by groups')
        if self.out_channels % self.groups != 0:
            raise ValueError('out_channels should be divisible by groups')

    def __call__(self, x: torch.Tensor):
        self.X = x
        self.ih, self.iw = self.X.shape[-2], self.X.shape[-1]
        batch_size, in_channels, in_height, in_width = x.size()
        out_height = (in_height + 2 * self.padding[0] - self.dilation[0] * (self.kernel_size[0] - 1) - 1) // \
                     self.stride[0] + 1
        out_width = (in_width + 2 * self.padding[1] - self.dilation[1] * (self.kernel_size[1] - 1) - 1) // self.stride[
            1] + 1

        if self.padding[0] > 0 or self.padding[1] > 0:
            x = self.add_padding(x, self.padding[0])

        out = torch.zeros(batch_size, self.out_channels, out_height, out_width)

        for h in range(out_height):
            for w in range(out_width):
                h_start = h * self.stride[0]
                h_end = h_start + self.kernel_size[0]
                w_start = w * self.stride[1]
                w_end = w_start + self.kernel_size[1]
                receptive_field = x[:, :, h_start:h_end, w_start:w_end]

                out[:, :, h, w] = torch.sum(
                    receptive_field.unsqueeze(1) * self.weights.view(1, self.out_channels,
                                                                     self.in_channels // self.groups,
                                                                     *self.kernel_size),
                    dim=(2, 3, 4)
                ) + self.bias.view(1, self.out_channels)

        return out

    def prepare_subMatrix(self, X, Kh, Kw, s):
        B, C, ih, iw = X.shape
        sh, sw = s

        Oh = (ih - Kh) // sh + 1
        Ow = (iw - Kw) // sw + 1

        strides = (C * ih * iw, iw * ih, iw * sh, sw, iw, 1)
        subM = torch.as_strided(X,
                                shape=(B, C, Oh, Ow, Kh, Kw),
                                strides=strides
                                )
        return subM

    def padding_backward(self,
                         dXp: torch.Tensor):

        B, C, ih, iw = self.X.shape
        dX = dXp[:, :, self.padded_height:ih, self.padded_width:iw]
        return dX

    def convolve(self, X: torch.Tensor,
                 K: torch.Tensor,
                 s: Tuple = (1, 1),
                 mode: str = 'back'):

        F, Kc, Kh, Kw = K.shape
        subM = self.prepare_subMatrix(X, Kh, Kw, s)

        if mode == 'front':
            return torch.einsum('fckl,mcijkl->mfij', K, subM)
        elif mode == 'back':
            return torch.einsum('fdkl,mcijkl->mdij', K, subM)
        elif mode == 'param':
            return torch.einsum('mfkl,mcijkl->fcij', K, subM)

    def dz_D_dx(self,
                dZ: torch.Tensor,
                ih: int,
                iw: int):
        _, _, Hd, Wd = dZ.shape
        ph = ih - Hd + self.kernel_size[0] - 1
        pw = iw - Wd + self.kernel_size[0] - 1

        dZ_Dp = self.add_padding(dZ, ph)

        # Rotate the Kernel by 180 degrees
        k_rotated = self.weights[:, :, ::-1, ::-1]

        # convolve w.r.t k_rotated
        dXp = self.convolve(dZ_Dp, k_rotated, mode='back')

        dX = self.padding_backward(dXp)
        return dX

    def backward(self,
                 dZ: torch.Tensor):
        Xp: torch.Tensor = self.add_padding(self.X, self.padding)
        B, C, ih, iw = Xp.shape

        # dZ -> dZ_D_dX
        dX = self.dz_D_dx(dZ, ih, iw)

        # gradient dK
        _, _, Hd, Wd = dZ.shape
        ph = self.ih - Hd - self.kernel_size[0] + 1
        pw = self.iw - Wd - self.kernel_size[0] + 1

        dZ_Dp = self.add_padding(dZ, padding=ph)

        self.dweights = self.convolve(Xp, dZ_Dp, mode='param')

        # gradient db
        self.dbias = dZ.sum(0)

        return dX

    def parameters(self):
        return [self.weights] + ([] if self.bias is None else [self.bias])


In [177]:
conv = Conv2d(3, 5, 2)
conv.weights, conv.bias

(tensor([[[[-0.3372, -0.1607],
           [-0.0424,  0.2792]],
 
          [[ 0.0431,  0.5649],
           [-1.8187,  0.3276]],
 
          [[ 0.1595,  0.3155],
           [-0.4101, -0.5286]]],
 
 
         [[[ 0.7688, -1.4299],
           [-1.6796, -1.0166]],
 
          [[ 0.7357, -0.2954],
           [ 0.0655,  0.7476]],
 
          [[-1.7967, -0.3187],
           [ 0.3662, -0.2843]]],
 
 
         [[[ 0.3952,  0.3623],
           [-1.9322,  0.1265]],
 
          [[-0.6430, -0.7050],
           [-1.0528, -0.3704]],
 
          [[-0.9510, -0.3699],
           [-1.1384, -1.4173]]],
 
 
         [[[-0.3879,  0.5395],
           [ 0.5747, -0.1485]],
 
          [[ 0.2446, -1.0037],
           [ 1.1414,  0.6541]],
 
          [[ 0.5049,  1.0136],
           [-1.0679, -1.5061]]],
 
 
         [[[ 1.8986, -0.1898],
           [-0.5832, -1.3480]],
 
          [[-0.4289,  0.0443],
           [-0.5146,  1.4133]],
 
          [[ 0.2470,  0.1782],
           [ 0.3316, -0.5827]]]], requires_grad

In [186]:
x = np.random.randn(1,1,5,5)
x

array([[[[ 1.18893149, -0.9696258 ,  1.06130319,  0.31716785,
          -0.61831145],
         [-0.50221894, -0.27220749,  1.38423068, -0.21969117,
           0.06406922],
         [ 0.00484239,  1.70762968,  0.39114741,  0.04030697,
           0.30507207],
         [-0.42158428, -1.44251038, -0.03865119, -0.28017898,
          -0.19429141],
         [ 0.30450748,  0.78276913,  0.00453206,  0.29052367,
           1.36977019]]]])

In [188]:
import numpy as np
def dilate2D(X, Dr=(1,1)):
    dh, dw = Dr # Dilate rate
    m, C, H, W = X.shape
    Xd = np.insert(arr=X, obj=np.repeat(np.arange(1,W), dw-1), values=0, axis=-1)
    print(Xd)
    Xd = np.insert(arr=Xd, obj=np.repeat(np.arange(1,H), dh-1), values=0, axis=-2)
    return Xd

dilate2D(x, (2,2))

[[[[ 1.18893149  0.         -0.9696258   0.          1.06130319
     0.          0.31716785  0.         -0.61831145]
   [-0.50221894  0.         -0.27220749  0.          1.38423068
     0.         -0.21969117  0.          0.06406922]
   [ 0.00484239  0.          1.70762968  0.          0.39114741
     0.          0.04030697  0.          0.30507207]
   [-0.42158428  0.         -1.44251038  0.         -0.03865119
     0.         -0.28017898  0.         -0.19429141]
   [ 0.30450748  0.          0.78276913  0.          0.00453206
     0.          0.29052367  0.          1.36977019]]]]


array([[[[ 1.18893149,  0.        , -0.9696258 ,  0.        ,
           1.06130319,  0.        ,  0.31716785,  0.        ,
          -0.61831145],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [-0.50221894,  0.        , -0.27220749,  0.        ,
           1.38423068,  0.        , -0.21969117,  0.        ,
           0.06406922],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [ 0.00484239,  0.        ,  1.70762968,  0.        ,
           0.39114741,  0.        ,  0.04030697,  0.        ,
           0.30507207],
         [ 0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ],
         [-0.42158428,  0.        , -1.44251038,  0.        ,
          -0.03865119,  0.        , -0.28017898,  

## Fully Connected Layer

### Linear

In [164]:
class Linear:
    def __init__(self, 
                fan_in: int,
                fan_out : int,
                bias = True):
        self.weight = torch.randn((fan_in, fan_out)) // fan_in ** 0.5
        self.bias = torch.randn(fan_out) if bias else None

    def __call__(self, 
                X: torch.Tensor):

        self.out = X @ self.weight
        if self.bias is not None:
            self.out += self.bias
        return self.out

    def parameters(self):
        return [self.weight] + ([] if self.bias is None else [self.bias])



In [169]:
li = Linear(3,10)
x = torch.randn(10,3)


In [171]:
x, li(x)

(tensor([[ 0.3764, -0.7310,  0.6046],
         [ 0.0692, -1.4089,  0.2280],
         [ 0.3872, -0.2472,  1.0910],
         [-1.2647,  0.5164,  1.8031],
         [ 1.9894, -0.3805,  0.8868],
         [ 0.1882, -0.8929, -1.8867],
         [-1.6680, -0.1485,  0.4404],
         [ 0.8268,  0.2494,  0.0408],
         [ 0.0881,  0.0684,  1.7387],
         [ 0.5513, -0.0030, -0.3670]]),
 tensor([[ 0.0577,  2.1041,  1.1866,  0.5189, -0.1753,  0.6206, -1.9982, -1.7773,
          -1.7881, -1.9033],
         [ 1.1122,  2.7820,  3.6027,  1.1968,  0.2013,  0.6206, -1.3144, -1.7773,
          -0.4264, -1.5268],
         [-0.9125,  1.6202, -0.7646,  0.0351, -0.6616,  0.6206, -2.4953, -1.7773,
          -2.7691, -2.3897],
         [-2.3882,  0.8566, -2.0642, -0.7285, -1.3738,  0.6206, -1.5555, -1.7773,
          -2.5930, -3.1018],
         [-0.5750,  1.7536, -1.6919,  0.1684, -0.4575,  0.6206, -3.8934, -1.7773,
          -4.0338, -2.1855],
         [ 2.7109,  2.2660,  6.6812,  0.6808,  2.3160,  0.6206,

In [172]:
li.weight

tensor([[ 0.,  0., -1.,  0.,  0.,  0., -1.,  0., -1.,  0.],
        [-1., -1., -2., -1.,  0.,  0.,  0.,  0., -1.,  0.],
        [-1.,  0., -2.,  0., -1.,  0., -1.,  0., -1., -1.]])

In [174]:
li.bias

tensor([-0.0687,  1.3730,  1.3101, -0.2121,  0.4293,  0.6206, -1.0171, -1.7773,
        -1.5381, -1.2987])