In [1]:
import torch

In [ ]:
#layer 1

In [5]:
in_channels = 3
out_channels = 10
kernel_size = (3,3)

In [7]:
#initiate weights 
torch.randn((out_channels,in_channels,*kernel_size))

tensor([[[[-1.0495e+00, -1.7580e+00,  4.1795e-01],
          [ 1.8725e+00, -9.8038e-01,  9.4437e-01],
          [-1.4191e+00,  2.3699e+00,  4.4351e-01]],

         [[ 1.1183e-01,  1.2399e+00, -2.5661e-01],
          [ 8.4793e-01,  6.2487e-01,  1.3730e-01],
          [-9.5623e-02,  2.2914e-01,  4.5365e-02]],

         [[ 7.9021e-01,  3.2863e-01,  8.7401e-01],
          [ 1.5657e+00,  1.3363e-01, -9.9822e-01],
          [-5.7637e-01, -3.6445e-01, -2.0969e+00]]],


        [[[ 2.3385e+00, -2.9221e-01,  1.9251e-01],
          [-4.3402e-01, -1.0931e+00,  2.2725e-01],
          [-4.4886e-01,  6.0577e-01, -1.5331e+00]],

         [[-3.5683e-01, -2.5788e+00,  9.2207e-01],
          [ 6.5727e-01,  1.0595e+00, -1.5112e-01],
          [-8.7363e-01,  5.0214e-01,  2.1334e-02]],

         [[ 3.0374e-01,  3.1106e-01,  8.2254e-01],
          [-7.3743e-01, -1.5710e-01, -1.2523e+00],
          [ 1.3881e+00, -1.4177e-01, -6.2086e-02]]],


        [[[ 1.7163e-01, -1.9476e-01,  4.0807e-02],
          [ 7.1

In [8]:
# layer2

In [9]:
in_channels = 10
out_channels = 10
kernel_size = (3,3)

#initialize weights
torch.randn((out_channels, in_channels, *kernel_size))

tensor([[[[ 9.7780e-01, -2.5650e+00,  4.5908e-01],
          [-6.5964e-01, -5.5390e-01, -2.3156e-01],
          [ 4.4518e-01, -8.4500e-01, -5.1839e-01]],

         [[-3.5526e-03,  1.5240e+00, -3.9857e-02],
          [-7.3219e-02, -1.2916e+00,  1.7444e-01],
          [ 7.9504e-02,  3.3009e-01, -2.5717e-02]],

         [[ 1.3604e+00, -1.9060e+00,  1.0994e+00],
          [-7.2749e-01, -2.0732e+00, -7.7894e-01],
          [-1.4691e+00,  1.6194e-01, -7.7943e-01]],

         [[-7.7918e-01,  1.1310e+00,  1.0559e+00],
          [ 3.0552e-01,  6.0789e-02, -6.7630e-01],
          [ 2.9063e-01, -1.1181e+00,  4.2425e-01]],

         [[-2.0772e+00, -5.5466e-01, -8.3448e-01],
          [-5.0678e-02,  9.0030e-01,  2.0078e-01],
          [-3.3117e-01, -1.2373e+00, -4.3185e-01]],

         [[-6.7557e-01, -6.3573e-01, -1.1711e+00],
          [ 1.2524e-02,  4.4757e-01,  1.8580e-01],
          [ 2.9108e-01, -1.2670e-01, -2.6969e-01]],

         [[ 1.6968e+00, -2.0797e+00,  2.1210e-01],
          [-6.6815e

In [2]:
import torch

In [25]:
class MaxPoolLayer:
    def __init__(self, size):
        self.last_input = None
        self.size = size

    def forward(self, x):
        self.last_input = x
        batch_size, channels, height, width = x.shape
        output_height = height // self.size
        output_width = width // self.size
        output = torch.zeros((batch_size, channels, output_height, output_width))
        print(output.shape)
        print(batch_size, channels)

        for i in range(output_height):
            for j in range(output_width):
                region = x[:, :, i * self.size:(i + 1) * self.size, j * self.size:(j + 1) * self.size].clone()
                print(region)
                print(region.view(batch_size, channels, -1))
                output[:, :, i, j] = torch.max(region.view(batch_size, channels, -1), dim=2)[0]

        return output

maxp = MaxPoolLayer(2)
maxp.forward(torch.randn(1,3,8,8))

torch.Size([1, 3, 4, 4])
1 3
tensor([[[[ 1.6427,  1.0322],
          [ 0.4579,  0.0647]],

         [[ 0.1017,  0.0574],
          [-1.0971, -0.0121]],

         [[ 0.5391, -0.7971],
          [-0.0425, -0.1239]]]])
tensor([[[ 1.6427,  1.0322,  0.4579,  0.0647],
         [ 0.1017,  0.0574, -1.0971, -0.0121],
         [ 0.5391, -0.7971, -0.0425, -0.1239]]])
tensor([[[[ 0.9477, -2.1046],
          [-0.8918,  1.1653]],

         [[ 0.3947,  0.0235],
          [-0.5901, -1.0602]],

         [[-0.5812,  2.2962],
          [ 0.4634,  0.1835]]]])
tensor([[[ 0.9477, -2.1046, -0.8918,  1.1653],
         [ 0.3947,  0.0235, -0.5901, -1.0602],
         [-0.5812,  2.2962,  0.4634,  0.1835]]])
tensor([[[[ 1.4651,  0.3512],
          [-0.8567,  0.9281]],

         [[-0.3210,  1.1427],
          [ 1.3828,  0.6929]],

         [[-1.3889,  1.3208],
          [ 0.9103,  2.2272]]]])
tensor([[[ 1.4651,  0.3512, -0.8567,  0.9281],
         [-0.3210,  1.1427,  1.3828,  0.6929],
         [-1.3889,  1.3208,  0

tensor([[[[ 1.6427,  1.1653,  1.4651,  2.1653],
          [ 1.3022,  0.9019, -0.5103,  1.2618],
          [ 1.8199,  2.3357,  0.9530,  2.7921],
          [ 1.7597,  1.2933,  1.6829,  1.5644]],

         [[ 0.1017,  0.3947,  1.3828,  1.7951],
          [ 1.8039,  1.7464,  1.8264,  1.4221],
          [ 0.9518,  0.1586, -0.1511,  1.1992],
          [ 0.9165,  1.0605,  1.1929,  0.8534]],

         [[ 0.5391,  2.2962,  2.2272,  1.7785],
          [ 1.5228,  1.7821,  1.2115, -0.2284],
          [ 0.9773,  0.0335,  0.8344,  1.5670],
          [ 1.2896,  0.4775,  0.3441,  0.8723]]]])

In [7]:
torch.randn(1,3,2,2),  torch.randn(1,3,2,2).view(1,3,-1) 

(tensor([[[[ 0.5773,  0.2666],
           [-0.7162, -2.4324]],
 
          [[ 1.1050, -0.5656],
           [-0.7531, -0.5193]],
 
          [[ 1.1093,  0.4929],
           [ 0.8521,  0.3785]]]]),
 tensor([[[ 1.6661, -0.1036, -1.9657, -0.7794],
          [ 0.5083, -0.5641, -0.9532,  2.4542],
          [ 1.8015,  1.1530,  0.6015, -1.0125]]]))

In [12]:
torch.max(torch.randn(1,3,2,2).view(1,3,-1) , dim = 1
         )

torch.return_types.max(
values=tensor([[0.7720, 0.4830, 1.1073, 1.2307]]),
indices=tensor([[0, 1, 1, 2]]))

In [16]:
out = torch.zeros(1,3,4,4)
out[:,:,1,1] = torch.max(torch.randn(1,3,2,2).view(1,3,-1) , dim = 2
         )[0]

In [17]:
out

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 1.4582, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.1321, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.5029, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]]])